cluster.name: smarthome-cluster
node.name: node-1
path.data: /usr/share/elasticsearch/data
network.host: 0.0.0.0
transport.host: 127.0.0.1
bootstrap.memory_lock: true
http.port: 9200
discovery.type: single-node
discovery.zen.minimum_master_nodes: 1
xpack.license.self_generated.type: basic