setup:
  kibana.host: "kibana:5601"
  dashboards.enabled: true
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: true
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: elastic
  password: ${ES_PASSWORD}
logging.to_files: false